layout_spectrum: 0.7680851
name: MadeBySimmons
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.3085106
color:
  brandStrength: 0.493617
  lightness: 1
  saturation: 0.4595745
  rhythmicContrast: 1
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
