typography_spectrum: 0.7125733469147235
color:
  brandStrength: 0.749628021614626
  lightness: 0.8181418
  saturation: 0.0990217
  rhythmicContrast: 1
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
layout_spectrum: 0.3965325551107526
name: MadeBySimmons
navigation:
  - name: Hozier Lane
    id: 19fe9cbf-36fb-4c86-8891-405ea875b937
    type: content
  - name: Shelley Beach
    id: 3f3e9b3f-b4f8-4782-955c-61cb5e432ec3
    type: content
  - name: Baloons @ Sunrise
    id: 30406440-4d35-40b7-be09-c59044d7ba48
    type: content
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: A Site For Many Things
description: 'After-all, why not?'
